id: P9FF05422
initial_creation_type: input
source_metadata:
  Title: Buddhist Himalaya
  Editor: Shakya, M. B.
  Publisher: Nagarjuna Institute of Exact Methods
  Place of Publication: Nepal
  Year: '2000'
  Āryatriskandha sūtram:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T15:59:46.670334'
last_modified_at: '2022-03-08T15:59:46.670344'
